default:
        image: python:3.6

before_script:
        - pip install -r requirements.txt
        - pip install nuitka
        - echo $CI_COMMIT_SHORT_SHA

stages:
        - build
job:
        stage: build
        script:
                - python -m nuitka --standalone --show-scons --show-progress --experimental=use_pefile --experimental=use_pefile_recurse --experimental=use_pefile_fullrecurse --include-plugin-directory=/usr/local/lib/python3.6/site-packages/jinja2 --include-plugin-directory=./templates --include-plugin-directory=./static app.py
                - ls
                - ls app.dist
                - cp -r templates app.dist
                - cp -r static app.dist
                - cp orm.db app.dist
                - curl -O 'https://gist.githubusercontent.com/tavinus/93bdbc051728748787dc22a58dfe58d8/raw/cloudsend.sh' && chmod +x cloudsend.sh
                - tar -czvf app.tar.gz app.dist
                - ./cloudsend.sh ./app.tar.gz https://emma.cloud.tabdigital.eu/s/wawd73BZ32XGwsK

