default:
        image: python:3.6

stages:
        - build
job:
        stage: build
        script: pip install nuitka;
                pip install requirements.txt;
                python -m nuitka --standalone --follow-imports --show-scons --show-progress app.py

