image:
  - Visual Studio 2015

install:
  - cmd: C:\Python37-x64\python -m pip install nuitka pyinstaller
  - cmd: C:\Python37-x64\python -m pip install -r requirements.txt
  - cmd: C:\Python37\python -m pip install nuitka pyinstaller
  - cmd: C:\Python37\python -m pip install -r requirements.txt


build_script:
  - cmd: C:\Python37-x64\python -m nuitka --assume-yes-for-downloads --standalone --experimental=use-pefile --include-package=jinja2 --include-package=jinja2.ext --plugin-enable=gevent wsgi.py
  - ps: cp orm.db wsgi.dist
  - ps: cp -r static wsgi.dist
  - ps: cp -r templates wsgi.dist
  - ps: Compress-Archive -Path wsgi.dist -DestinationPath windows-x64-nuitka.zip
  - cmd: C:\Python37-x64\python -m PyInstaller --onefile wsgi.py
  - ps: cp orm.db dist
  - ps: cp -r static dist
  - ps: cp -r templates dist
  - ps: Compress-Archive -Path dist -DestinationPath windows-x64-pyinstaller.zip
  - cmd: C:\Python37\python -m PyInstaller --onefile wsgi.py
  - ps: cp orm.db dist
  - ps: Compress-Archive -Path dist -DestinationPath windows-x86-pyinstaller.zip

after_build:
  - ps: ls

artifacts:
  - path: '*.zip'

deploy:
  - provider: GitHub
      auth_token:
        secure: aoDGrsLzM0zY8pD8+qIVoe1MeuIrm2aKnZWbZY+t2Y3PgNTMaXleAYsx45V2AOKg
      on:
        APPVEYOR_REPO_TAG: true
      artifact: windows-x64-nuitka.zip
  - provider: GitHub
      auth_token:
        secure: aoDGrsLzM0zY8pD8+qIVoe1MeuIrm2aKnZWbZY+t2Y3PgNTMaXleAYsx45V2AOKg
      on:
        APPVEYOR_REPO_TAG: true
      artifact: windows-x64-pyistaller.zip
  - provider: GitHub
      auth_token:
        secure: aoDGrsLzM0zY8pD8+qIVoe1MeuIrm2aKnZWbZY+t2Y3PgNTMaXleAYsx45V2AOKg
      on:
        APPVEYOR_REPO_TAG: true
      artifact: windows-x64-pyinstaller.zip


