image:
  - Visual Studio 2015

install:
  - cmd: C:\Python37\python -m pip install nuitka

build_script:
  - cmd: C:\Python37\python -m nuitka --assume-yes-for-downloads --standalone wsgi.py

deploy:
  provider: GitHub
  auth_token: 40a793c3d513c78216597a028716023c7e153998
  on:
    branch: master # release from master branch only
    APPVEYOR_REPO_TAG: true # deploy on tag push only
