image:
  - Visual Studio 2015

install:
  - cmd: C:\Python37\python -m pip install nuitka

build_script:
  - cmd: C:\Python37\python -m nuitka --assume-yes-for-downloads --standalone wsgi.py

after_build:
  - ps: Compress-Archive -Path wsgi.dist -DestinationPath windows-x64-nuitka.zip


deploy:
  provider: GitHub
  auth_token:
    secure: 83Zm/2bg6mjHmK862aC54oIZJx/G2ZkxY7oYQg5pG9LlQYAx+bS+5QD6vzBqBQjl
  on:
    branch: master                 # release from master branch only
    APPVEYOR_REPO_TAG: true        # deploy on tag push only
  artifact: windows-x64-nuitka.zip

