image:
  - Visual Studio 2015

install:
  - cmd: C:\Python37\python -m pip install nuitka
  - cmd: C:\Python37\python -m pip install -r requirements.txt

build_script:
  - cmd: C:\Python37\python -m nuitka --assume-yes-for-downloads --standalone --experimental=use-pefile wsgi.py

after_build:
  - ps: Compress-Archive -Path wsgi.dist -DestinationPath windows-x64-nuitka.zip


deploy:
  release: test-$(APPVEYOR_REPO_TAG_NAME)
  provider: GitHub
  auth_token:
    secure: aoDGrsLzM0zY8pD8+qIVoe1MeuIrm2aKnZWbZY+t2Y3PgNTMaXleAYsx45V2AOKg
  on:
    branch: master                 # release from master branch only
    APPVEYOR_REPO_TAG: true        # deploy on tag push only
  artifact: windows-x64-nuitka.zip

